FORMAT: 1A

# APIs

API for consuming information about world cups between 1930 and 2014.

## Group Worldcups

## Movie collection [/movies]

### List all Movies [GET]

List movies in reverse order of publication.

- Response 200 (application/json)


## Group Users